name: Build and Release

on:
  push:
    tags:
      - 'v*'  # triggers on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npx ng build --configuration=production --base-href /ssg/andreas-gajdosik/feed-em/

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        
      - name: Zip build artifacts with version
        run: |
            mkdir -p packaged
            zip -r packaged/feed-em-${{ github.ref_name }}.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: packaged/feed-em-${{ github.ref_name }}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}